version: 0.0
os: linux
files:
  - source: ./studymama-0.0.1-SNAPSHOT.jar
    destination: /tmp
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "studymama-container"
          ContainerPort: 8080
