version: 2.1

orbs:
  python: circleci/python@1.2
  docker: circleci/docker@1.5.0

jobs:
  build:
    docker:
      - image: cimg/python:3.8
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          name: python test
          command: |
            python --version
            pip list
      - run:
          name: docker-compose and run
          command: | 
            echo y | docker image prune
            echo y | docker container prune
            docker-compose -f docker-compose.yml up --build -d
      - run:
          name: show docker images
          command: docker images
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker tag studymama $DOCKER_USER/studymama:$CIRCLE_SHA1
            docker tag studymama $DOCKER_USER/studymama:latest
            docker push $DOCKER_USER/studymama:$CIRCLE_SHA1
            docker push $DOCKER_USER/studymama:latest
            #echo "$REMOTE_PRIVATE_KEY" > id_rsa
            cat id_rsa
            python test.py $REMOTE_HOST $DOCKER_USER
          
          
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
